---

- name: Enabled/Started firewall
  service: name=firewalld state=started enabled=yes

- name: Set modprobe
  shell: modprobe br_netfilter

- name: Active transparent masquerading
  firewalld: masquerade=yes permanent=true state=enabled

- name: Reload firewall
  command: firewall-cmd --reload

#- name: Config kubernetes traffic
#  blockinfile:
#    path: "/etc/sysctl.d/k8s.conf"
#    block: |
#      net.bridge.bridge-nf-call-ip6tables = 1
#      net.bridge.bridge-nf-call-iptables = 1
- name: Config kubernetes traffic
  template: src=k8s.conf.j2 dest=/etc/sysctl.d/k8s.conf owner=root group=root

- name: Apply changes
  command: sysctl --system
