---
- name: Add kubernetes repo
  blockinfile:
     create: yes
     path: "/etc/yum.repos.d/kubernetes.repo"
     block: |
            [kubernetes]
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            exclude=kubelet kubeadm kubectl

- name: Install kubeadm, kubectl y kubelet
  command: 
    cmd: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    warn: no

- name: Start kubelet service
  service:
      name: "kubelet"
      state: started
      enabled: yes
