---
- name: Create directory /srv/nfs
  file: path=/srv/nfs state=directory mode=777 owner=root group=root
- name: Make file /etc/exports
  template: src=exports.j2 dest=/etc/exports owner=root group=root
- name: Apply new config exportfs -rs
  command: exportfs -rs
