- name: 'Restarting firewalld'
  systemd:
    name: firewalld
    state: restarted
    enabled: true
    daemon_reload: true
- name: Open ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - nfs
    - rpc-bind
    - mountd

- name: Reload firewall
  command: firewall-cmd --reload
