---
#- name: Create users in master
#  hosts: master
#  gather_facts: false
#  become: true
#  roles:
#     - master_create_users

- name: Configuration previous tasks
  hosts: all
  gather_facts: false
  become: true
  roles:
    - configuration_tasks

- name: Install NFS server
  hosts: nfs
  gather_facts: false
  become: true
  roles:
    - nfs_configuration

- name: Kubernetes - Common configuration
  hosts: all
  gather_facts: false
  become: true
  roles:
    - kubernetes_config

- name: Kubernetes - Master
  hosts: master
  gather_facts: false
  become: true
  roles:
    - kubernetes_master
